inherit_from: .rubocop_todo.yml
require:
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - "config.ru"
    - "bin/**"
    - "lib/**"
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "vendor/**/*"
Lint/RaiseException:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
AsciiComments:
  Enabled: false
Documentation:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
Metrics/ClassLength:
  Max: 200
Metrics/ModuleLength:
  Max: 200
Layout/LineLength:
  Max: 250
  AllowHeredoc: true
  AllowURI: true
  IgnoredPatterns:
    - '\A\s*?#'
RSpec/NestedGroups:
  Max: 6
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Max: 30
